name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  QAT_PW_SWAG_URL: ${{ vars.QAT_PW_SWAG_URL }}
  QAT_PW_SWAG_USERNAME: ${{ vars.QAT_PW_SWAG_USERNAME }}
  QAT_PW_SWAG_PASSWORD: ${{ secrets.QAT_PW_SWAG_PASSWORD }}
  QAT_PW_WEATHER_BIT_API_KEY: ${{ secrets.QAT_PW_WEATHER_BIT_API_KEY }}
  QAT_PW_WEATHER_BIT_URL: ${{ vars.QAT_PW_WEATHER_BIT_URL }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
